- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Edit postgresql.conf for remote access
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: '^#?listen_addresses =.*$'
    line: "listen_addresses = '*'"
  notify: restart postgresql

- name: Create pg_hba.conf for remote access
  blockinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    block: |
      host    all             all             0.0.0.0/0               md5
  notify: restart postgresql

- name: Create database backup
  become_user: postgres
  shell: pg_dump --format=custom --file=/tmp/xyz.backup --dbname=postgres --host=target1@192.168.1.15
  become: true
  file:
    path: /tmp/
    state: directory
    mode: "0777"
  register: pg_dump_output

- name: Copy backup file to target host
  copy:
    src: /tmp/abc.backup
    dest: /tmp/
  delegate_to: target2@192.168.1.10

- name: Restore database on target host
  become_user: postgres
  shell: pg_restore --verbose --clean --no-acl --no-owner --host=target2@192.168.1.10 --dbname=postgres /tmp/xyz.backup
